[package]
name = "notes"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.43", features = ["derive"] }
duckdb = { version = "1.3.2", features = ["bundled"] }
prettytable-rs = "0.10.0"
